baseURL = "https://ctrl-alt.fail/"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true
languageCode = "en"
theme = "hugo-theme-stack"
title = "ctrl-alt-fail"

[permalinks]
  post = "/:slug/"

[params]
  description = "Foobar"

[Params.Sidebar]
  compact = false
  emoji = "ğŸ§™ğŸ»â€â™‚ï¸"
  subtitle = "Decoding life one byte at a time."

[Params.Footer]
  since = 2025
  customText = "Custom Text"

[minify]
  minifyOutput = true