baseURL = "https://ctrl-alt.fail/"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true
languageCode = "en"
theme = "hugo-theme-stack"
title = "ctrl-alt-fail"

[permalinks]
post = "/:slug/"

[params]
description = "Foobar"

[Params.Sidebar]
compact = false
emoji = "ğŸ§™ğŸ»â€â™‚ï¸"
subtitle = "Decoding life one byte at a time."

[article]
headingAnchor = false
math = false
readingTime = true

[article.license]
enabled = true
default = "Licensed under CC BY-NC-SA 4.0"

## Widgets
[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 10

[widgets.page]
type = "toc"

[opengraph.twitter]
site = ""
card = "summary_large_image"

[defaultImage.opengraph]
enabled = false
local = false
src = ""

[colorScheme]
toggle = true
default = "auto"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true

## Comments
[comments]
enabled = false
provider = "disqus"

[Params.Footer]
since = 2025
customText = "Custom Text"

[minify]
minifyOutput = true
